name: hosea46
favicon: null
layout_spectrum: 0.22315502213314176
typography_spectrum: 0.42731466819532216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.40892914263531566
  lightness: 0.9503491874784231
  saturation: 0.8851422753650695
  rhythmicContrast: 0.1884566757362336
purpose: []
