name: hosea46
favicon: null
layout_spectrum: 0.25647
typography_spectrum: 0.15698
title: 'Hosea 4:6'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3fa8f4'
    - '#000000'
    - '#00ffff'
    - '#0080ff'
    - '#008080'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
